### ISSUE TITLE
files not opening 

### ISSUE THREAD

**Issue by soslucasoss** [VioletGiraffe/FasterThanSight#55]
Hello, I hope this message won't create any problems being posted here, I did not know how to reach creators otherwise. I have installed Faster Than Sight mac version 1.2.2 and all is fine until I try loading something like a pdf or rtf, docx, odt format to start reading... Nothing happens. I Only get from the log the following

readDataAndDecodeText unsupported extension "pdf"
Parsing text of 0 characters
Assigning the text took 0 ms
updatePauseValues took 0 ms
Stats: 
	Chapters: 0 
	Paragraphs: 0 
	Words: 0 
	Avg. paragraphs per chapter: nan 
	Max. paragraphs per chapter: 0 
	Avg. words per paragraph: nan 
	Max. words per paragraph: 0
Loading the file "/Users/a123/Downloads/Shunryu Suzuki-Roshi - Zen.pdf" took "0.0" seconds

What do you suggest doing? Thanks a lot for the great software and the help, I'd be very glad to get it working.

Best regards,
luca

**Comment by VioletGiraffe** [comment]
Hello, Luca! I only support plain text file (.TXT). This makes sense because the program cannot display any graphics, this technique in general is only meant for reading just plain text.
